# Generated by Django 5.1.1 on 2024-11-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate_aedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='descricao',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
