# Generated by Django 5.1.1 on 2024-11-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate_aedes', '0002_registro_imagem_alter_registro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
