# Generated by Django 5.1.1 on 2024-11-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combate_aedes', '0003_registro_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='imagem',
        ),
    ]
